const movieList = [
    {
        adult: false,
        backdrop_path: "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
        genre_ids: [878, 28, 12],
        id: 912649,
        original_language: "en",
        original_title: "Venom: The Last Dance",
        overview:
            "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
        popularity: 4714.877,
        poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
        release_date: "2024-10-22",
        title: "Venom: The Last Dance",
        video: false,
        vote_average: 6.622,
        vote_count: 523,
    },
    {
        adult: false,
        backdrop_path: "/gMQibswELoKmB60imE7WFMlCuqY.jpg",
        genre_ids: [27, 53, 9648],
        id: 1034541,
        original_language: "en",
        original_title: "Terrifier 3",
        overview:
            "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
        popularity: 4684.391,
        poster_path: "/63xYQj1BwRFielxsBDXvHIJyXVm.jpg",
        release_date: "2024-10-09",
        title: "Terrifier 3",
        video: false,
        vote_average: 7.2,
        vote_count: 673,
    },
    {
        adult: false,
        backdrop_path: "/v9acaWVVFdZT5yAU7J2QjwfhXyD.jpg",
        genre_ids: [16, 878, 10751],
        id: 1184918,
        original_language: "en",
        original_title: "The Wild Robot",
        overview:
            "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
        popularity: 2957.48,
        poster_path: "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
        release_date: "2024-09-12",
        title: "The Wild Robot",
        video: false,
        vote_average: 8.533,
        vote_count: 2472,
    },
    {
        adult: false,
        backdrop_path: "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
        genre_ids: [18, 27, 878],
        id: 933260,
        original_language: "en",
        original_title: "The Substance",
        overview:
            "Have you ever dreamt of a better version of yourself? You, only better in every way. You should try this new product. It's called The Substance. It changed my life.",
        popularity: 2126.642,
        poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
        release_date: "2024-09-07",
        title: "The Substance",
        video: false,
        vote_average: 7.312,
        vote_count: 1493,
    },
    {
        adult: false,
        backdrop_path: "/zViRwl3ySscZnbXZJ2Q9wq3SeUG.jpg",
        genre_ids: [16, 878, 12, 10751],
        id: 698687,
        original_language: "en",
        original_title: "Transformers One",
        overview:
            "The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.",
        popularity: 1756.832,
        poster_path: "/iHPIBzrjJHbXeY9y7VVbEVNt7LW.jpg",
        release_date: "2024-09-11",
        title: "Transformers One",
        video: false,
        vote_average: 8.2,
        vote_count: 560,
    },
    {
        adult: false,
        backdrop_path: "/uGmYqxh8flqkudioyFtD7IJSHxK.jpg",
        genre_ids: [18, 80, 53],
        id: 889737,
        original_language: "en",
        original_title: "Joker: Folie à Deux",
        overview:
            "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him.",
        popularity: 1708.687,
        poster_path: "/if8QiqCI7WAGImKcJCfzp6VTyKA.jpg",
        release_date: "2024-10-01",
        title: "Joker: Folie à Deux",
        video: false,
        vote_average: 5.7,
        vote_count: 1391,
    },
    {
        adult: false,
        backdrop_path: "/llIXQAndg5kB6SWlp6ouUdO7Zxd.jpg",
        genre_ids: [12, 36, 28, 18, 10749, 53],
        id: 1084736,
        original_language: "fr",
        original_title: "Le Comte de Monte-Cristo",
        overview:
            "Edmond Dantes becomes the target of a sinister plot and is arrested on his wedding day for a crime he did not commit. After 14 years in the island prison of Château d’If, he manages a daring escape. Now rich beyond his dreams, he assumes the identity of the Count of Monte-Cristo and exacts his revenge on the three men who betrayed him.",
        popularity: 1510.541,
        poster_path: "/zw4kV7npGtaqvUxvJE9IdqdFsNc.jpg",
        release_date: "2024-06-28",
        title: "The Count of Monte-Cristo",
        video: false,
        vote_average: 8.3,
        vote_count: 747,
    },
    {
        adult: false,
        backdrop_path: "/2fxnTXr8NwyTFkunkimJkGkhqfy.jpg",
        genre_ids: [18, 28, 27],
        id: 1118031,
        original_language: "es",
        original_title: "Apocalipsis Z: el principio del fin",
        overview:
            "When a kind of rabies that transforms people into aggressive creatures spreads across the planet, Manel isolates himself at home with his cat, relying on his wits to survive; but soon they must go out in search of food, by land and by sea, dodging many dangers.",
        popularity: 1007.076,
        poster_path: "/wIGJnIFQlESkC2rLpfA8EDHqk4g.jpg",
        release_date: "2024-10-04",
        title: "Apocalypse Z: The Beginning of the End",
        video: false,
        vote_average: 6.7,
        vote_count: 218,
    },
    {
        adult: false,
        backdrop_path: "/csQSGH0QU8D3Ov5YLEYuHep8ihA.jpg",
        genre_ids: [53, 12, 28, 878],
        id: 1196470,
        original_language: "fr",
        original_title: "Survivre",
        overview:
            "A couple celebrates their son’s birthday in the middle of the ocean on their boat. A violent storm hits and it brings up hungry creatures from the depths and they fight for their survival.",
        popularity: 937.904,
        poster_path: "/7fR3KxswtY8OHHZuOUB9td58CRX.jpg",
        release_date: "2024-06-19",
        title: "Survive",
        video: false,
        vote_average: 5,
        vote_count: 38,
    },
    {
        adult: false,
        backdrop_path: "/begseNUKhZcc05Bc1UggaX5GeES.jpg",
        genre_ids: [28, 53, 80],
        id: 976734,
        original_language: "en",
        original_title: "Canary Black",
        overview:
            "Top level CIA agent Avery Graves is blackmailed by terrorists into betraying her own country to save her kidnapped husband. Cut off from her team, she turns to her underworld contacts to survive and help locate the coveted intelligence that the kidnappers want.",
        popularity: 885.79,
        poster_path: "/hhiR6uUbTYYvKoACkdAIQPS5c6f.jpg",
        release_date: "2024-10-10",
        title: "Canary Black",
        video: false,
        vote_average: 6.4,
        vote_count: 184,
    },
    {
        adult: false,
        backdrop_path: "/qYvOcinXcnebhmCxYeivurh91T1.jpg",
        genre_ids: [27, 878, 53],
        id: 827931,
        original_language: "en",
        original_title: "Time Cut",
        overview:
            "A teen in 2024 accidentally time-travels to 2003, days before a masked killer murders her sister. Can she change the past without destroying the future?",
        popularity: 814.142,
        poster_path: "/gzMFMmpJHOmOFKsAhSDac62Dyg2.jpg",
        release_date: "2024-10-29",
        title: "Time Cut",
        video: false,
        vote_average: 5.77,
        vote_count: 183,
    },
    {
        adult: false,
        backdrop_path: "/cRdA9xjHBbobw4LJFsQ3j1CgpVq.jpg",
        genre_ids: [27, 53],
        id: 663712,
        original_language: "en",
        original_title: "Terrifier 2",
        overview:
            "A year after the Miles County massacre, Art the Clown is resurrected by a sinister entity. Art returns home, where he must hunt down and destroy teenage Sienna and her younger brother Jonathan on Halloween. As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",
        popularity: 749.335,
        poster_path: "/8gLhu8UFPZfH2Hv11JhTZkb9CVl.jpg",
        release_date: "2022-10-06",
        title: "Terrifier 2",
        video: false,
        vote_average: 6.8,
        vote_count: 1972,
    },
    {
        adult: false,
        backdrop_path: "/rOmUuQEZfPXglwFs5ELLLUDKodL.jpg",
        genre_ids: [35, 28, 14],
        id: 845781,
        original_language: "en",
        original_title: "Red One",
        overview:
            "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous bounty hunter in a globe-trotting, action-packed mission to save Christmas.",
        popularity: 740.774,
        poster_path: "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg",
        release_date: "2024-10-31",
        title: "Red One",
        video: false,
        vote_average: 7.7,
        vote_count: 23,
    },
    {
        adult: false,
        backdrop_path: "/1aOPPkXASkd2By3EKIw66Ilx5qF.jpg",
        genre_ids: [28, 53],
        id: 1094974,
        original_language: "en",
        original_title: "Take Cover",
        overview:
            "A burned-out professional sniper finds himself trapped in an all-glass penthouse by a lethal competitor and must find a way to survive and escape with little to no cover between him and the killer.",
        popularity: 689.199,
        poster_path: "/xNLiMNyFzKTL9PVIEulG55Hei8j.jpg",
        release_date: "2024-10-04",
        title: "Take Cover",
        video: false,
        vote_average: 6.7,
        vote_count: 38,
    },
    {
        adult: false,
        backdrop_path: "/6Rjsm5khNaYa4Gnw4iHnGX2E34T.jpg",
        genre_ids: [27, 53],
        id: 1063877,
        original_language: "en",
        original_title: "Don't Move",
        overview:
            "A grieving woman in a secluded forest encounters a killer who injects her with a paralytic drug. As her body shuts down, her fight for survival begins.",
        popularity: 668.172,
        poster_path: "/cRDJxdnRb7ikKd6fVJTrGeaL34v.jpg",
        release_date: "2024-10-24",
        title: "Don't Move",
        video: false,
        vote_average: 6.501,
        vote_count: 387,
    },
    {
        adult: false,
        backdrop_path: "/jT4KqFTrR2ofpUUwzKCIn4uYWXp.jpg",
        genre_ids: [28, 53],
        id: 1331375,
        original_language: "en",
        original_title: "Dominique",
        overview:
            "Dominique, a well-trained assassin, flees from her troubled past in an attempt to begin a new life in South America. However, she soon finds herself in a town plagued with violence and corruption. Facing brutal attacks from the police and mafia, Dominique must decide whether to protect herself or an innocent family that has taken her in.",
        popularity: 661.937,
        poster_path: "/29uKScAbQuKsMEdAn12a6BmvFn7.jpg",
        release_date: "2024-10-11",
        title: "Dominique",
        video: false,
        vote_average: 7.5,
        vote_count: 25,
    },
    {
        adult: false,
        backdrop_path: "/uLqNGzJwnj8JKkKuRM2dHWJKCtc.jpg",
        genre_ids: [28, 27, 53],
        id: 1029235,
        original_language: "en",
        original_title: "Azrael",
        overview:
            "In a world where no one speaks, a devout female hunts down a young woman who has escaped her imprisonment. Recaptured by its ruthless leaders, Azrael is due to be sacrificed to pacify an ancient evil deep within the surrounding wilderness.",
        popularity: 605.082,
        poster_path: "/qpdFKDvJS7oLKTcBLXOaMwUESbs.jpg",
        release_date: "2024-09-27",
        title: "Azrael",
        video: false,
        vote_average: 6.1,
        vote_count: 116,
    },
    {
        adult: false,
        backdrop_path: "/m1MifWpNjOU1g8UfIyNSI2dMFZf.jpg",
        genre_ids: [16, 10751, 35, 27],
        id: 1371727,
        original_language: "en",
        original_title: "Sing: Thriller",
        overview:
            'Buster Moon dreams up a star-studded spectacle set to Michael Jackson\'s "Thriller" in this animated short featuring characters from the hit "Sing" films.',
        popularity: 578.435,
        poster_path: "/i77OInTKcrnRlAozFOaB6D5mk15.jpg",
        release_date: "2024-10-16",
        title: "Sing: Thriller",
        video: false,
        vote_average: 7.4,
        vote_count: 74,
    },
    {
        adult: false,
        backdrop_path: "/hd1TvTUGjkoYoqvXYfSBpI5Ri9B.jpg",
        genre_ids: [16, 28, 12, 878],
        id: 1159311,
        original_language: "ja",
        original_title: "僕のヒーローアカデミア THE MOVIE ユアネクスト",
        overview:
            "In a society devastated by the effects of an all-out war between heroes and villains, a mysterious giant fortress suddenly appears, engulfing towns and people one after another. Then, a man reminiscent of All Might, the 'symbol of peace', stands in front of Izuku and his friends...",
        popularity: 521.875,
        poster_path: "/8rdB1wkheEMMqcY8qLAKjCMPcnZ.jpg",
        release_date: "2024-08-02",
        title: "My Hero Academia: You're Next",
        video: false,
        vote_average: 6.9,
        vote_count: 47,
    },
    {
        adult: false,
        backdrop_path: "/vOwezqxpHjBpA5nJIWbapm9Qtgd.jpg",
        genre_ids: [28, 35, 80],
        id: 616446,
        original_language: "en",
        original_title: "Brothers",
        overview:
            "A reformed criminal's attempt at going straight is derailed when he reunites with his sanity-testing twin brother on a road trip for the score of a lifetime. Dodging bullets, the law, and an overbearing mother along the way, they must heal their severed family bond before they end up killing each other.",
        popularity: 457.72,
        poster_path: "/Akweo95FGyDpucYVT81h0SbX8Ky.jpg",
        release_date: "2024-10-10",
        title: "Brothers",
        video: false,
        vote_average: 6.255,
        vote_count: 149,
    },
];

export default movieList;
